FROM alpine:3.15
RUN apk add cmatrix
CMD [ "/usr/bin/cmatrix" ]

LABEL date="19.01.2022"
LABEL version="2022.01"
LABEL maintainer="dlindvai"
LABEL description="Simple Matrix image based on Alpine Linux."
